app:
  build: ./
  working_dir: /project
  links:
    - mongo
  volumes:
    - ./:/project
  command: forever app.js -l app.log
  environment:
    NODE_ENV: 'prod'
  ports:
    - "5100:3000"

mongo:
  image: mongo:latest
  command: "/entrypoint.sh mongod --smallfiles"

mongocli:
  image: mongo:latest
  links:
    - mongo
  volumes:
    - ./:/project